'\" t
.\"     Title: aldabad
.\"    Author: [see the "Authors" section]
.\" Generator: DocBook XSL Stylesheets v1.75.1 <http://docbook.sf.net/>
.\"      Date: 11/20/2010
.\"    Manual: Aldaba Reference Guide
.\"    Source: Aldaba
.\"  Language: English
.\"
.TH "ALDABAD" "8" "11/20/2010" "Aldaba" "Aldaba Reference Guide"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
aldabad \- Single Packet Authorization and Port Knocking server
.SH "SYNOPSIS"
.HP \w'\fBaldabad\fR\ 'u
\fBaldabad\fR [\fIOptions\fR]
.SH "DESCRIPTION"
.\" Aldaba: description of
.PP
Aldaba is an open\-source Port Knocking and Single Packet Authorization system\&. This document describes the latest version of Aldaba Server, part of the Aldaba Suite, available from
\m[blue]\fB\%http://www.aldabaknocking.com\fR\m[]
.SH "OPTIONS SUMMARY"
.PP
The following option summary is the output of Aldaba Server when run with no arguments\&. It\'s a quick cheatsheet that lists the most common options\&.
.\" summary of options (Aldaba)
.\" command-line options: of Aldaba
.sp
.if n \{\
.RS 4
.\}
.nf
  Aldaba Knocking Server 0\&.2\&.1 \- (C) Luis MartinGarcia, 2010\&.
  http://www\&.aldabaknocking\&.com || aldabaknocking@gmail\&.com

  Usage: aldabad <\-P passphrase> [Options]

  Parameters:
     \-P, \-\-passphrase <pass>  : Passphrase used to generate the crypto keys\&.
  Options:
     \-\-pk, \-\-spa              : Technique ["PK", "SPA"(default)]\&.
     \-t, \-\-target\-ports <seq> : Sequence of dest ports [comma separated list]\&.
     \-f, \-\-field <field>      : Covert channel protocol header field\&.
     \-c  \-\-cipher <algorithm> : Encryption algorithm ["Twofish", "AES", \&.\&.\&.]
     \-i, \-\-interface <name>   : Network interface to listen on\&.
     \-v, \-\-verbosity <level>  : Level of verbosity [0\-9 (Default)]\&.
     \-l, \-\-logging <level>    : Logging level [0\-9]\&.
     \-4, \-\-ipv4               : Use IP version 4 addresses
     \-6, \-\-ipv6               : Use IP version 6 addresses
     \-C, \-\-config <path>      : Read configuration from file\&.
     \-I, \-\-interactive        : Run interactively, not as a system daemon\&.
     \-h, \-\-help               : Display usage information\&.
     \-V, \-\-version            : Display current version\&.
     \-\-promiscuous            : Put network interface intro promiscuous mode

   
  Examples:
     aldabad \-P "Squeamish Ossifrage"
     aldabad \-t 3,14,159,2653 \-v9 \-i eth1
     aldabad \-6 \-\-cipher twofish \-\-promisc
  For more information please refer to manual page aldabad(8)\&.

.fi
.if n \{\
.RE
.\}
.\" 
.\" 
.SH "MODES OF OPERATION"
.PP
.PP
\fB\-\-spa\fR (Single Packet Authorization Mode)
.RS 4
This option tells Aldaba Server to run in SPA mode\&. Single Packet Authorization is the technique that allows users request access to a given port number on the server, using a single authentication message\&. That message, called the SPA authentication message, is transmitted to the server in a single UDP datagram\&. This technique provides strong authentication and is the default operation mode in Aldaba\&.
.RE
.PP
\fB\-\-pk\fR (Port Knocking Mode)
.RS 4
This option tells Aldaba Server to run in PK mode\&. Like SPA, Port Knocking lets users request access to a given port\&. However, the authentication message is transmitted stealthily, dividing it, and encoding each part in the headers of a TCP SYN packet\&. Port Knocking authentications are more difficult to detect from an attacker\'s point of view\&. However, the security provided by this technique is often weaker than in SPA\&.
.RE
.SH "SINGLE PACKET AUTHORIZATION"
.PP
.PP
\fB\-t \fR\fB\fIport\fR\fR, \fB\-\-target\-port \fR\fB\fIport\fR\fR (Set target port number)
.RS 4
This option specifies the destination port number that incoming SPA messages are expected to be directed to\&. If no port is supplied, Aldaba will pick one automatically, based on the supplied passphrase\&.
.RE
.SH "PORT KNOCKING"
.PP
.PP
\fB\-t \fR\fB\fIports\fR\fR, \fB\-\-target\-ports \fR\fB\fIports\fR\fR (Set knock sequence)
.RS 4
List of expected knocks\&. These should be the same ports used by Aldaba Client\&. The list should be comma separated and have no spaces in it (eg: \-t 1337,2600,8086,6800)\&. Also, ports must be unique\&. The number of ports needed depends on the type of authentication and the header field that is used to create the covert channel\&. If you don\'t supply the correct number of ports Aldaba will tell you how many is expecting\&.
.sp
Note that this parameter is completely optional and may safely be omitted\&. When not supplied, the sequence of ports is generated automatically, deriving it from the supplied passphrase\&. A give passphrase will always produce the same port sequence, in both client and server\&.
.RE
.PP
\fB\-f \fR\fB\fIid\fR\fR, \fB\-\-field \fR\fB\fIid\fR\fR (Set covert channel header field)
.RS 4
This option specifies the protocol header field used by the client to encode the PK authentication message\&. Currently the following fields are available:
.PP
ip\-tos
.RS 4
IPv4 Type of Service\&. (8 bits)\&.
.RE
.PP
ip\-id
.RS 4
IPv4 Identification\&. (16 bits)\&.
.RE
.PP
tcp\-ack
.RS 4
TCP Acknowledgement Number (32 bits)
.RE
.PP
tcp\-seq (Default)
.RS 4
TCP Sequence Number (32 bits)
.RE
.PP
tcp\-sport
.RS 4
TCP Source Port (16 bits)
.RE
.PP
tcp\-win
.RS 4
TCP Window Size (16 bits)
.RE
.PP
tcp\-urp
.RS 4
TCP Urgent Pointer (16 bits)
.RE
.sp
.RE
.PP
\fB\-A \fR\fB\fItype\fR\fR, \fB\-\-auth \fR\fB\fItype\fR\fR (Set authentication strength)
.RS 4
This option specifies the strength and security of the authentication\&. Currently there are two different possibilities:
.PP
light (Default)
.RS 4
Light authentication provides basic, but fast and effective client authentication\&. It requires very few packets to be sent to the server, minimizing the risk of packet loss and providing a good response time\&. However, although the the security of this authentication may be enough for some cases, it can be broken by skilled attackers\&. Systems that require high levels of security should use the strong authentication discussed below\&.
.RE
.PP
strong
.RS 4
Strong authentication provides a much more secure and robust client authentication\&. It requires the transmission of a higher number of packets, which increases the risk of packet loss, but provides effective protection against replay attacks, and significantly reduces the risk of poisoning attacks\&. Systems that require high levels of security should use this type of authentication\&.
.RE
.sp
.RE
.SH "CRYPTOGRAPHY OPTIONS"
.PP
\fB\-P \fR\fB\fIstring\fR\fR, \fB\-\-passphase \fR\fB\fIstring\fR\fR (Set passphrase)
.RS 4
Passphrase to be used to generate the necessary cryptographic keys (one for message authentication and one for message encryption)\&. It must be at least 8 characters long and have a maximum of 256 characters\&. If it contains spaces, it should be enclosed in double quotes (e\&.g: \-k "Use this to encrypt it all")\&. Special characters should be escaped using a backslash\&. Passphrases longer than 256 characters are valid but will be truncated\&. Cryptographic keys are derived from this passphrase using the PBKDF2 algorithm\&.
.RE
.PP
\fB\-c\fR, \fB\-\-cipher\fR (Set encryption algorithm)
.RS 4
Algorithm to be used to encrypt authentication data\&. Currently the following algorithms are supported:
.PP
Blowfish
.RS 4
Symmetric ; 64\-bit block size ; Very Fast\&.
.RE
.PP
Rijndael
.RS 4
Symmetric ; 128\-bit block size ; Fast ; AES Standard\&. (DEFAULT)
.RE
.PP
Serpent
.RS 4
Symmetric ; 128\-bit block size ; Medium ; AES Contest finalist (2nd position)
.RE
.PP
Twofish
.RS 4
Symmetric 128\-bit block size ; Fast ; AES Contest finalist (3rd position)
.RE
.sp
All algorithms use 256\-bit keys\&. Note that Port Knocking mode with Light authentication MUST it Blowfish because it requires a block size of 64 bits\&.
.RE
.SH "NETWORKING OPTIONS"
.PP
\fB\-i \fR\fB\fIname\fR\fR, \fB\-\-interface \fR\fB\fIname\fR\fR (Set network interface)
.RS 4
This option sets the network interface that should be used to capture incoming packets\&. Any network interface supported by libpcap can be used\&. If no interface is specified Aldaba Server will try to use the most suitable one\&.
.RE
.PP
\fB\-\-promiscuous \fR (Set promiscuous mode)
.RS 4
Puts the network card into promiscuous mode\&. By default the network interface is left in non\-promiscuous mode, unless it was already in promiscuous mode\&.
.RE
.SH "OUTPUT OPTIONS"
.PP
\fB\-v\fR\fB[\fIlevel\fR]\fR, \fB\-\-verbose \fR\fB[\fIlevel\fR]\fR (Increase or set verbosity level)
.RS 4
Increases the verbosity level, causing Aldaba to print more information during its execution\&. There are 9 levels of verbosity (0 to 8)\&. Every instance of
\fB\-v\fR
increments the verbosity level by one (from its default value, level 4)\&. Every instance of option
\fB\-q\fR
decrements the verbosity level by one\&. Alternatively you can specify the level directly, as in
\fB\-v3\fR
or
\fB\-v\-1\fR\&. These are the available levels:
.PP
Level 0
.RS 4
No output at all\&.
.RE
.PP
Level 1
.RS 4
Parsing Error messages\&.
.RE
.PP
Level 2
.RS 4
Fatal error messages\&. (Default)\&.
.RE
.PP
Level 3
.RS 4
Warnings\&.
.RE
.PP
Level 4
.RS 4
Information about knocking attempts \&.
.RE
.PP
Level 5
.RS 4
Information about current configuration \&.
.RE
.PP
Level 6
.RS 4
Important debug information\&.
.RE
.PP
Level 7
.RS 4
Any debug information\&.
.RE
.PP
Level 8
.RS 4
Reserved for future use\&.
.RE
.PP
Level 9
.RS 4
Reserved for future use\&.
.RE
.sp
.RE
.PP
\fB\-q\fR\fB[\fIlevel\fR]\fR, \fB\-\-reduce\-verbosity \fR\fB[\fIlevel\fR]\fR (Decrease verbosity level)
.RS 4
Decreases the verbosity level, causing Aldaba to print less information during its execution\&.
.RE
.PP
\fB\-l\fR\fB[\fIlevel\fR]\fR, \fB\-\-logging \fR\fB[\fIlevel\fR]\fR (Set logging level)
.RS 4
Controls the level of logging\&. Logs are sent via syslog\&. Entries use the prefix "aldabad" and the current PID of the process\&. There are 10 different levels (0 to 9)\&. Higher levels include all lower levels\&.
.PP
Level 0
.RS 4
No logging at all\&.
.RE
.PP
Level 1
.RS 4
Failed authentication attempts\&.
.RE
.PP
Level 2
.RS 4
Successful authentication attempts\&.
.RE
.PP
Level 3
.RS 4
Fatal error messages\&. (Default)\&.
.RE
.PP
Level 4
.RS 4
Warnings\&.
.RE
.PP
Level 5
.RS 4
Information about current configuration \&.
.RE
.PP
Level 6
.RS 4
Important debug information\&.
.RE
.PP
Level 7
.RS 4
Any debug information\&.
.RE
.PP
Level 8
.RS 4
Reserved for future use\&.
.RE
.PP
Level 9
.RS 4
Reserved for future use\&.
.RE
.sp
.RE
.PP
\fB\-\-debug \fR (Debug)
.RS 4
Automatically sets maximum verbosity level and disables daemon mode\&.
.RE
.PP
\fB\-\-quiet \fR (Quiet)
.RS 4
Automatically sets verbose and logging levels to 0\&. No output or logs will be generated\&.
.RE
.SH "MISCELLANEOUS OPTIONS"
.PP
\fB\-C \fR\fB\fIpath\fR\fR, \fB\-\-config \fR\fB\fIpath\fR\fR (Read configuration from file)
.RS 4
Tells Aldaba server to read configuration from a specific configuration file\&. Supplied path may be absolute or relative to the current directory\&. Alternatively, it is possible to run the server simply like "aldabad
\fBstart\fR", what makes it read the default configuration file (typically stored in /etc/aldabad/conf/aldabad\&.conf or /usr/local/etc/aldabad/conf/aldabad\&.conf)
.RE
.PP
\fB\-I \fR, \fB\-\-interactive \fR (Interactive mode)
.RS 4
Forces Aldaba Server to run interactively instead of in daemon mode\&. By default it runs as a system daemon\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR (Display Version)
.RS 4
Displays current version and quits\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR (Display Help)
.RS 4
Displays help information and quits\&.
.RE
.SH "BUGS"
.PP
Please, report any bugs you find through the Aldaba development mailing list or directly to aldabaknocking@gmail\&.com\&. Please try to include as much information as possible\&. In general it\'s a good idea to include the output of the command "uname \-a", the version of Aldaba you are using and a brief description of the topology of the network you are using Aldaba from (subnets, routers, firewalls, etc)\&. See
\m[blue]\fB\%http://http://www.aldabaknocking.com/development\fR\m[]
for more details\&.
.SH "AUTHORS"
.PP
Luis MartinGarcia
luis\&.mgarc@gmail\&.com
(\m[blue]\fB\%http://www.aldabaknocking.com\fR\m[])
